name: CI/CD for Nuxt 3

on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2

        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm
      - name: Generate
        run: yarn generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
